var data = {
    "Imprint/Promotion Label:": [],
    "Morgan Wallen": [],
    "Kendrick Lamar": [],
    "Kali Uchis": [],
    "The Weeknd": [],
    "SZA": [
        "TDE",
        "RCA"
    ],
    "Sabrina Carpenter": [],
    "Benson Boone": [],
    "Drake": [],
    "Teddy Swims": [],
    "Chappell Roan": [],
    "Lady Gaga": [],
    "Billie Eilish": [],
    "Luke Combs": [],
    "Shaboozey": [
        "Republic",
        "Empire"
    ],
    "Jelly Roll": [],
    "Fuerza Regida": [],
    "Post Malone": [],
    "P1Harmony": [],
    "Alex Warren": [],
    "Taylor Swift": [],
    "Doechii": [],
    "Forrest Frank": [],
    "Bad Bunny": [],
    "Bruno Mars": [],
    "Zach Bryan": [],
    "Blake Shelton": [],
    "Chris Stapleton": [],
    "BigXthaPlug": [],
    "Fleetwood Mac": [],
    "Ed Sheeran": [],
    "Tate McRae": [],
    "Tyler, The Creator": [],
    "Metallica": [],
    "Hozier": [],
    "Jessie Murph": [
        "Disruptor",
        "Columbia"
    ],
    "Myles Smith": [],
    "Gracie Abrams": [],
    "Bailey Zimmerman": [],
    "Lola Young": [],
    "Miley Cyrus": [],
    "Ella Langley": [],
    "Ariana Grande": [],
    "Nirvana": [],
    "Riley Green": [],
    "Linkin Park": [],
    "Radiohead": [],
    "Michael Jackson": [
        "Steeltown",
        "Motown",
        "Epic",
        "Legacy",
        "Sony",
        "MJJ Productions"
    ],
    "Zach Top": [],
    "Frank Ocean": [],
    "Megan Moroney": [],
    "Leon Thomas": [],
    "Pink Floyd": [],
    "PARTYNEXTDOOR": [],
    "Kane Brown": [],
    "sombr": [],
    "Playboi Carti": [],
    "ROSE": [],
    "Chris Brown": [],
    "Charli xcx": [],
    "Ghost": [],
    "AC/DC": [],
    "Brandon Lake": [],
    "Thomas Rhett": [],
    "Noah Kahan": [],
    "Jason Aldean": [],
    "Eric Church": [],
    "The Marias": [],
    "Queen": [],
    "Lorde": [],
    "Coldplay": [],
    "The Beatles": [],
    "Rihanna": [],
    "Lainey Wilson": [],
    "Arcade Fire": [],
    "Mariah The Scientist": [],
    "Tucker Wetmore": [],
    "Neton Vega": [],
    "Karol G": [],
    "Eagles": [],
    "Tito Double P": [],
    "GloRilla": [],
    "Eminem": [],
    "Tommy Richman": [],
    "Alice In Chains": [],
    "Journey": [],
    "Red Hot Chili Peppers": [],
    "Creed": [],
    "Lil Tecca": [],
    "Creedence Clearwater Revival": [],
    "3 Doors Down": [],
    "Lana Del Rey": [],
    "Deftones": [],
    "The Head And The Heart": [],
    "J. Cole": [],
    "Halsey": [],
    "Lynyrd Skynyrd": [],
    "PinkPantheress": [],
    "Gigi Perez": [],
    "Arctic Monkeys": []
};var lastUpdated = "05/28";