var data = {
    "Morgan Wallen": [],
    "ATEEZ": [],
    "Kendrick Lamar": [],
    "Sabrina Carpenter": [
        "Hollywood",
        "Island"
    ],
    "SZA": [],
    "The Weeknd": [],
    "Benson Boone": [],
    "Alex Warren": [],
    "Luke Combs": [
        "River House Artists",
        "Sony Music Nashville"
    ],
    "Metallica": [],
    "Billie Eilish": [],
    "ENHYPEN": [],
    "Taylor Swift": [],
    "Shaboozey": [],
    "Brandon Lake": [],
    "Chappell Roan": [],
    "Drake": [
        "OVO Sound",
        "Republic",
        "Young Money",
        "Cash Money",
        "Aspire"
    ],
    "Teddy Swims": [],
    "Jelly Roll": [],
    "Tate McRae": [],
    "The Beach Boys": [],
    "Lil Tecca": [],
    "Lady Gaga": [],
    "Zach Bryan": [],
    "Post Malone": [],
    "Fleetwood Mac": [],
    "GloRilla": [],
    "Ed Sheeran": [],
    "Chris Stapleton": [],
    "Jessie Murph": [],
    "Bruno Mars": [],
    "Doechii": [],
    "BigXthaPlug": [],
    "Bad Bunny": [],
    "Hozier": [],
    "Tyler, The Creator": [],
    "Myles Smith": [],
    "Bailey Zimmerman": [],
    "Chris Brown": [],
    "Fuerza Regida": [],
    "sombr": [],
    "Riley Green": [],
    "Nirvana": [],
    "Ella Langley": [],
    "Coldplay": [
        "Fierce Panda",
        "Parlophone",
        "Nettwerk",
        "Capitol",
        "Atlantic"
    ],
    "Lil Wayne": [],
    "Radiohead": [],
    "Leon Thomas": [],
    "Kane Brown": [],
    "King Gizzard And The Lizard Wizard": [],
    "Michael Jackson": [
        "Steeltown",
        "Motown",
        "Epic",
        "Legacy",
        "Sony",
        "MJJ Productions"
    ],
    "j-hope": [],
    "Gracie Abrams": [],
    "Lola Young": [],
    "Miley Cyrus": [],
    "Ariana Grande": [],
    "Oliver Anthony Music": [],
    "SEVENTEEN": [],
    "Linkin Park": [
        "Warner Bros",
        "Machine Shop"
    ],
    "Forrest Frank": [],
    "My Chemical Romance": [],
    "Ravyn Lenae": [],
    "Zach Top": [],
    "Creedence Clearwater Revival": [],
    "Calum Hood": [],
    "Charli xcx": [],
    "Lainey Wilson": [],
    "Led Zeppelin": [],
    "Turnstile": [],
    "Eagles": [],
    "iTZY": [],
    "Frank Ocean": [],
    "Queen": [],
    "The Beatles": [],
    "Red Hot Chili Peppers": [],
    "Thomas Rhett": [],
    "Megan Moroney": [],
    "Jason Aldean": [],
    "Mac Miller": [],
    "The Cure": [],
    "Mariah The Scientist": [],
    "Van Morrison": [],
    "Playboi Carti": [],
    "The Marias": [],
    "Stray Kids": [],
    "Twenty One Pilots": [],
    "Addison Rae": [
        "Columbia",
        "As Long As I'm Dancing"
    ],
    "Travis Scott": [
        "Grand Hustle",
        "Epic",
        "Very GOOD Beats",
        "Cactus Jack"
    ],
    "Tucker Wetmore": [],
    "The Doobie Brothers": [],
    "AC/DC": [],
    "Sam Hunt": [],
    "Pink Floyd": [],
    "Conan Gray": [],
    "Max McNown": [],
    "The Red Clay Strays": [],
    "Tyler Childers": [],
    "Journey": [],
    "Noah Kahan": [],
    "Lil Baby": []
};var lastUpdated = "06/25";