var data = {
    "Playboi Carti": [],
    "Kendrick Lamar": [],
    "Lady Gaga": [],
    "Morgan Wallen": [],
    "Sabrina Carpenter": [],
    "Chappell Roan": [],
    "SZA": [],
    "LE SSERAFIM": [],
    "Billie Eilish": [],
    "Doechii": [],
    "The Weeknd": [],
    "Drake": [],
    "Tate McRae": [],
    "Teddy Swims": [],
    "Bruno Mars": [],
    "Taylor Swift": [],
    "Tyler, The Creator": [],
    "Luke Combs": [],
    "Bad Bunny": [],
    "Jelly Roll": [],
    "Benson Boone": [],
    "Gracie Abrams": [],
    "Shaboozey": [],
    "Post Malone": [],
    "Travis Scott": [],
    "Hozier": [],
    "Zach Bryan": [],
    "Alex Warren": [],
    "Fleetwood Mac": [],
    "Coheed And Cambria": [],
    "Charli xcx": [],
    "Lola Young": [],
    "Chris Stapleton": [],
    "Metallica": [],
    "JENNIE": [],
    "Noah Kahan": [],
    "Bailey Zimmerman": [],
    "Nirvana": [],
    "Myles Smith": [],
    "Frank Ocean": [],
    "Chris Brown": [],
    "Radiohead": [],
    "ROSE": [],
    "Zach Top": [],
    "Tito Double P": [],
    "Neton Vega": [],
    "Ed Sheeran": [],
    "Sleep Token": [],
    "Linkin Park": [],
    "BigXthaPlug": [],
    "Future": [],
    "Michael Jackson": [],
    "GloRilla": [],
    "Stray Kids": [],
    "Charley Crockett": [],
    "Ariana Grande": [],
    "PARTYNEXTDOOR": [],
    "Jisoo": [],
    "Steven Wilson": [],
    "Warren Zeiders": [],
    "Riley Green": [],
    "Spiritbox": [],
    "Eminem": [],
    "Rihanna": [],
    "Deftones": [],
    "Mac Miller": [],
    "Brandon Lake": [],
    "Lainey Wilson": [],
    "Blake Shelton": [],
    "Kane Brown": [],
    "Miley Cyrus": [],
    "J. Cole": [],
    "YEJI": [],
    "Coldplay": [],
    "Pink Floyd": [],
    "Tommy Richman": [],
    "Ella Langley": [],
    "Sexyy Red": [],
    "Dua Lipa": [],
    "Queen": [],
    "Cody Johnson": [],
    "Alice In Chains": [],
    "Eagles": [],
    "Gigi Perez": [],
    "Lana Del Rey": [],
    "Journey": [],
    "Lil Tecca": [],
    "Arctic Monkeys": [],
    "Tyla": [],
    "Harry Styles": [],
    "AC/DC": [],
    "Jason Aldean": [],
    "Jordan Davis": [],
    "Creed": [],
    "Red Hot Chili Peppers": [],
    "Led Zeppelin": [],
    "Fuerza Regida": [],
    "Dasha": [],
    "Goo Goo Dolls": [],
    "Summer Walker": []
};var lastUpdated = "03/26";